version: "3"
services:
  app:
    build: .
    container_name: "db-app"
    ports:
      - "8080:8080"
  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    ports:
      - "27017:27017"